# 1. What does Pandas stand for?

Pandas stand for Panel Data and Python Data Analysis

# 2. What are the two collections used in Pandas?

The two collections are DataFrames and Series

# 3. Name 4 things Pandas can do for us

Pandas can load, manipulate, prepare, and model data

# 4. To permanently sort a DataFrame, which keyboard should one use with the df.sort() method?

You should use "values"

# 5. What is a CSV

CSV is a file type that stands for "Comma Separated Values"

# 6. When cleaning data what values do we not like in our data?

We do not like null values

In [21]:
#Concatenate these 3 arrays into a new array named "newArray"

import numpy as np

array1 = np.array([[25, 16]])
array2 = np.array([[11,2], [13, 4]])
array3 = np.array([[7, 81], [5,6], [11,12]])

newArray = np.concatenate((array1, array2, array3), axis = 0)

print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [11]:
#Sort newArray in order into sortedArray

sortedArray = np.sort(newArray)

print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [24]:
#Reshape the 'sortedArray' into a new array
#called 'reshapedArray' so it has 2 dimensions with a size of 2,3

reshapedArray = sortedArray.reshape(2,2,3)

print(reshapedArray)

[[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]


In [33]:
#Unpack the array tuples into 4 well named variables

firstrow, secondrow = reshapedArray

firstrow0, firstrow1 = firstrow
secondrow0, secondrow1 = secondrow

print(firstrow0)
print(firstrow1)
print(secondrow0)
print(secondrow1)

[16 25  2]
[11  4 13]
[ 7 81  5]
[ 6 11 12]


In [37]:
#combine and sort the folloiwng arrays into one array called 'comboArray'

arrayOne = np.array([10,11,12,13,14,15,16,17])
arrayTwo = np.array([20,21,22,23,24,25,26,27])
arrayThree = np.array([0,1,2,3,4,5,6,7])

combArray = np.concatenate((arrayOne, arrayTwo, arrayThree))
comboArray = np.sort(combArray)

print(comboArray)




[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [57]:
#Take comoboArray and perform the following slice activities

sec1 = comboArray[2]
print(sec1)

sec2 = comboArray[3:]
print(sec2)

sec3 = comboArray[3:15]
print(sec3)

sec4 = comboArray[-6:]
print(sec4)

sec5 = comboArray[0:-10]
print(sec5)

sec6 = comboArray[16::2]
print(sec6)

sec7 = comboArray[::-5]
print(sec7)

2
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [85]:
#Using simply math operations, braoadcast addition, division, 
#and multiplication operations for these 2 arrays
mathArray1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

mathArray2 = np.array([[17.0, 70.0, 10.7]])

addArray = (mathArray1 + mathArray2)
divArray = (mathArray1 + mathArray2)
mulArray = (mathArray1 * mathArray2)

print(addArray)
print(divArray)
print(mulArray)

[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
[[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]


In [86]:
#Use the NumPy Arithmetic functions to do 
#the subtraction of the above two arrays

subArray = np.subtract(mathArray1, mathArray2)
print(subArray)

[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]


In [92]:
#Using modulo find all elements that are divisible by 3 from point 7

divByThree = mathArray1[mathArray1 % 3==0]
divByThree2 = mathArray2[mathArray2 % 3==0]
print(divByThree)
print(divByThree2)

[ 0.  0. 30. 24. 15.]
[]


In [97]:
#Using Series, create a DataFrame that looks like this:

import pandas as pd

ingredients = pd.Series(['flour', 'milk', 'eggs', 'spam'], name = 'Ingredients')
quantity = pd.Series([4,1,2,1], name = 'Quanitity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name = 'Unit')

Dinner = pd.concat([ingredients, quantity, unit], axis = 1)
print(Dinner)


  Ingredients  Quanitity   Unit
0       flour          4   cups
1        milk          1    cup
2        eggs          2  large
3        spam          1    can


In [99]:
#create a DataFrame named studentData

import pandas as pd

studentData = pd.DataFrame ({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
)

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [110]:
#Add a new column to the dataframe

studentData.insert(7, 'deserts', ['ice cream', 'cashew fudge', 'waffles', 'carrot halwa'], True )


In [111]:
#sort studentData in ascending order

studentData.sort_values(by = ['Name', 'address'], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets       deserts  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot  carrot halwa   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla       waffles   
0      Jai     5.1           Msc    Delhi   21         Dog     ice cream   
1  janusha     6.2            MA     Doha   23       Bunny  cashew fudge   

        deserts       deserts       deserts       deserts       deserts  \
3     ice cream     ice cream  carrot halwa  carrot halwa  carrot halwa   
2  cashew fudge  cashew fudge       waffles       waffles       waffles   
0       waffles       waffles     ice cream     ice cream     ice cream   
1  carrot halwa  carrot halwa  cashew fudge  cashew fudge  cashew fudge   

        deserts           sport  
3  carrot halwa         Cricket  
2       waffles  PaddleBoarding  
0     ice cream           Darts  
1  cashew fudge      Basketball  


In [112]:
#save DataFrame to a disc as a .csv file
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

In [144]:
# Using Pandas, make your own csv on vegetables...
import pandas as pd
vegetables = pd.DataFrame(['Peppers', 'Corn', 'Broccoli', 'Eggplant'], 
                          ['Red', 'Yellow', 'Green', 'Purple'])

flavor = pd.Series(['Spicy', 'Sweet', 'Bland', 'Bland'])

vegetables.loc[:, ['Flavor']] = ['Spicy', 'Sweet', 'Bland', 'Bland']

print(vegetables)

vegetables.to_csv('vegetable_information')



               0 Flavor
Red      Peppers  Spicy
Yellow      Corn  Sweet
Green   Broccoli  Bland
Purple  Eggplant  Bland
